Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    WEBSITE http://github.com/brain-image-library/singularity-gnuplot
    COPYRIGHT Copyright © 2024 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 6.0-patch-level-0

%post
    apk add --update gnuplot

%runscript
    gnuplot "$@"
